---
- name: Monitor failed logins for specific user and restart SSSD if needed
  hosts: all
  become: yes
  gather_facts: no

  vars:
    target_user: "john.doe"
    failure_threshold: 7
    log_file: /var/log/secure

  tasks:
    - name: Count failed login attempts for {{ target_user }}
      shell: "grep 'sssd.*authentication failure' {{ log_file }} | grep '{{ target_user }}' | wc -l"
      register: failed_count
      changed_when: false

    - name: Debug failed login count
      debug:
        msg: "User {{ target_user }} has {{ failed_count.stdout }} failed login attempts."

    - name: Restart SSSD if {{ target_user }} failed more than {{ failure_threshold }} times
      service:
        name: sssd
        state: restarted
      when: failed_count.stdout | int > failure_threshold
      notify: Log restart

  handlers:
    - name: Log restart
      shell: echo "SSSD restarted due to {{ target_user }} exceeding login failure threshold on {{ inventory_hostname }} at $(date)" >> /var/log/sssd_restart.log
